spring.application.name=libraryManagement_api
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloud.api.name=dvngvug3o
cloud.api.key=  269551121939751
cloud.api.secret= zkYsMGyzo0PRsvR0xA_RANoLtqc
spring.datasource.username=postgres
spring.datasource.password= #Ozunmba2ofB
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.config.import=secret.properties
