cloud.api.name=dvngvug3o
cloud.api.key=  269551121939751
cloud.api.secret= zkYsMGyzo0PRsvR0xA_RANoLtqc
spring.datasource.username=#Ozumnba2ofB
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
