name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch; adjust as necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu@latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: josephyisa/librarymanagementapi:latest

      - name: Set up Cloudinary
        run: |
          echo "CLOUDINARY_API_NAME=${{ secrets.cloudinaryApiName }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_KEY=${{ secrets.cloudinaryApiKey }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_SECRET=${{ secrets.cloudinaryApiSecret }}" >> $GITHUB_ENV
          echo "POSTGRES_USERNAME=${{ secrets.postgresUsername }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.postgresPassword }}" >> $GITHUB_ENV
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV